#camunda:
#  client:
#    mode: self-managed

camunda:
  client:
    mode: saas
    auth:
      client-id: <client-id>
      client-secret: <client-secret>
    cloud:
      cluster-id: <cluster-id>
      region: <region>